#import <UIKit/UIKit.h>
#import <objc/runtime.h>

@interface PHInspectorViewController : UIViewController
@property(nonatomic,copy) NSString *currentDetails;
@property(nonatomic,copy) NSString *currentSubtitle;
- (void)render:(BOOL)hierarchyMode;
- (void)backTapped;
@end

static NSString *PH2310Value(NSString *details, NSString *key){for(NSString *line in [details componentsSeparatedByString:@"\n"]){NSString*p=[key stringByAppendingString:@":"];if([line hasPrefix:p])return[[line substringFromIndex:p.length]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceCharacterSet];}return @"";}
static NSString *PH2310Code(NSString *details){NSString*html=PH2310Value(details?:@"",@"HTML");if(!html.length)return details?:@"";NSString*tag=@"div";NSRange o=[html rangeOfString:@"<"],c=o.location!=NSNotFound?[html rangeOfString:@">" options:0 range:NSMakeRange(o.location,html.length-o.location)]:NSMakeRange(NSNotFound,0);if(o.location!=NSNotFound&&c.location!=NSNotFound){NSString*inside=[html substringWithRange:NSMakeRange(o.location+1,c.location-o.location-1)];NSArray*p=[inside componentsSeparatedByCharactersInSet:NSCharacterSet.whitespaceCharacterSet];if(p.count&&[p[0]length])tag=p[0];}NSMutableString*a=[NSMutableString string];NSString*v=PH2310Value(details,@"ID");if(v.length)[a appendFormat:@" id=\"%@\"",v];v=PH2310Value(details,@"Classe");if(v.length)[a appendFormat:@" class=\"%@\"",v];v=PH2310Value(details,@"Tipo");if(v.length&&![v isEqualToString:tag])[a appendFormat:@" type=\"%@\"",v];v=PH2310Value(details,@"Link");if(v.length)[a appendFormat:@" href=\"%@\"",v];v=PH2310Value(details,@"Texto");if(v.length)return[NSString stringWithFormat:@"<%@%@>\n    %@\n</%@>",tag,a,v,tag];return[NSString stringWithFormat:@"<%@%@></%@>",tag,a,tag];}
static UIButton *PH2310FindButton(UIView*r,NSString*t){if(!r)return nil;if([r isKindOfClass:UIButton.class]&&[[((UIButton*)r)titleForState:UIControlStateNormal]isEqualToString:t])return(UIButton*)r;for(UIView*v in[r.subviews copy]){UIButton*b=PH2310FindButton(v,t);if(b)return b;}return nil;}
static UILabel *PH2310FindLabel(UIView*r){if(!r)return nil;if([r isKindOfClass:UILabel.class])return(UILabel*)r;for(UIView*v in[r.subviews copy]){UILabel*l=PH2310FindLabel(v);if(l)return l;}return nil;}
static void PH2310Refresh(PHInspectorViewController*vc){dispatch_async(dispatch_get_main_queue(),^{NSString*sub=vc.currentSubtitle?:@"";if([sub isEqualToString:@"Filtro JSON"]){UIButton*b=PH2310FindButton(vc.view,@"JSON");if(!b)b=PH2310FindButton(vc.view,@"Voltar");if(b){[b setTitle:@"Voltar" forState:UIControlStateNormal];UIImage*im=[UIImage systemImageNamed:@"chevron.left"];if(im)[b setImage:im forState:UIControlStateNormal];[b removeTarget:nil action:NULL forControlEvents:UIControlEventTouchUpInside];[b addTarget:vc action:@selector(backTapped) forControlEvents:UIControlEventTouchUpInside];b.contentHorizontalAlignment=UIControlContentHorizontalAlignmentLeft;b.contentEdgeInsets=UIEdgeInsetsMake(0,18,0,18);b.titleEdgeInsets=UIEdgeInsetsMake(0,8,0,0);}}if(![sub isEqualToString:@"Elemento Web selecionado"])return;NSString*code=PH2310Code(vc.currentDetails?:@"");if(!code.length)return;for(UIView*outer in[vc.view.subviews copy])for(UIView*v in[outer.subviews copy])if([v isKindOfClass:UIScrollView.class]){UILabel*l=PH2310FindLabel(v);if(l){l.text=code;l.font=[UIFont monospacedSystemFontOfSize:13 weight:UIFontWeightRegular];l.numberOfLines=0;[l sizeToFit];return;}}});}
static void(*PH2310OrigSelected)(id,SEL,NSString*);static void PH2310Selected(id self,SEL cmd,NSString*d){@try{[self setValue:d?:@"" forKey:@"currentDetails"];[self setValue:@"Elemento Web selecionado" forKey:@"currentSubtitle"];}@catch(__unused NSException*e){}if(PH2310OrigSelected)PH2310OrigSelected(self,cmd,d);PH2310Refresh((PHInspectorViewController*)self);}
static void(*PH2310OrigRender)(id,SEL,BOOL);static void PH2310Render(id self,SEL cmd,BOOL h){if(PH2310OrigRender)PH2310OrigRender(self,cmd,h);dispatch_async(dispatch_get_main_queue(),^{PH2310Refresh((PHInspectorViewController*)self);dispatch_async(dispatch_get_main_queue(),^{PH2310Refresh((PHInspectorViewController*)self);});});}
__attribute__((constructor))static void PH2310Install(void){dispatch_async(dispatch_get_main_queue(),^{Class c=NSClassFromString(@"PHInspectorViewController");if(!c)return;Method m=class_getInstanceMethod(c,@selector(showSelectedWebElement:));if(m){PH2310OrigSelected=(void*)method_getImplementation(m);if(PH2310OrigSelected!=(IMP)PH2310Selected)method_setImplementation(m,(IMP)PH2310Selected);}m=class_getInstanceMethod(c,@selector(render:));if(m){PH2310OrigRender=(void*)method_getImplementation(m);if(PH2310OrigRender!=(IMP)PH2310Render)method_setImplementation(m,(IMP)PH2310Render);}});}
