#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>
#import <Foundation/Foundation.h>
#import <objc/message.h>
#import <objc/runtime.h>
#import "PHOverlayManager.h"

/* WebHider 2.1: owns only the Hierarquia -> JSON -> Voltar state machine. */
static const void *PH26WantsJSONKey=&PH26WantsJSONKey;
static const void *PH26JSONScreenKey=&PH26JSONScreenKey;
static const void *PH26JSONTextKey=&PH26JSONTextKey;
static const void *PH26SelectedSelectorKey=&PH26SelectedSelectorKey;
static IMP PH26OriginalButton=NULL,PH26OriginalHierarchy=NULL,PH26OriginalBack=NULL,PH26OriginalDetails=NULL,PH26OriginalHighlight=NULL;
static BOOL PH26WantsJSON(id o){return[objc_getAssociatedObject(o,PH26WantsJSONKey)boolValue];}
static void PH26SetWantsJSON(id o,BOOL v){objc_setAssociatedObject(o,PH26WantsJSONKey,@(v),OBJC_ASSOCIATION_RETAIN_NONATOMIC);}
static BOOL PH26JSONScreen(id o){return[objc_getAssociatedObject(o,PH26JSONScreenKey)boolValue];}
static void PH26SetJSONScreen(id o,BOOL v){objc_setAssociatedObject(o,PH26JSONScreenKey,@(v),OBJC_ASSOCIATION_RETAIN_NONATOMIC);}
static NSString*PH26SelectedSelector(id m){return objc_getAssociatedObject(m,PH26SelectedSelectorKey)?:@"";}
static void PH26SetSelectedSelector(id m,NSString*s){objc_setAssociatedObject(m,PH26SelectedSelectorKey,s?:@"",OBJC_ASSOCIATION_COPY_NONATOMIC);}
static NSString*PH26JSONString(NSString*v){NSData*d=[NSJSONSerialization dataWithJSONObject:@[v?:@""] options:0 error:nil];NSString*a=[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding];return a.length>=2?[a substringWithRange:NSMakeRange(1,a.length-2)]:@"\"\"";}
static NSString*PH26FilterJSON(NSString*s){return[NSString stringWithFormat:@"{\n  \"action\": {\n    \"selector\": %@,\n    \"type\": \"css-display-none\"\n  },\n  \"trigger\": {\n    \"url-filter\": \".*\"\n  }\n}",PH26JSONString(s?:@"")];}
static NSString*PH26SelectorFromSelectedElementJS(void){return @"(function(){var e=document.querySelector('[data-projetoh-selected=\\\"1\\\"]');if(!e)e=document.querySelector('[data-projetoh-selected]');if(!e)return '';function esc(s){try{return CSS.escape(s)}catch(_){return s.replace(/[^a-zA-Z0-9_-]/g,'\\\\$&')}}function unique(s){try{return document.querySelectorAll(s).length===1}catch(_){return false}}function classes(n){if(!n||typeof n.className!=='string')return [];return n.className.trim().split(/\\s+/).filter(function(c){return c&&['row','col','flex','flex-center','justify-center','items-center','no-wrap','q-focus-helper','q-icon','q-btn','q-btn__content','q-btn-item','non-selectable','notranslate','material-icons'].indexOf(c)<0})}var n=e;while(n&&n.nodeType===1&&n!==document.body){if(n.id){var id='[id=\\\"'+esc(n.id)+'\\\"]';if(unique(id))return id}var cs=classes(n);for(var i=0;i<cs.length;i++){var c='.'+esc(cs[i]);if(unique(c))return c}n=n.parentElement}if(e.id){var eid='[id=\\\"'+esc(e.id)+'\\\"]';if(unique(eid))return eid}var own=classes(e);for(var j=0;j<own.length;j++){var oc='.'+esc(own[j]);if(unique(oc))return oc}return e.tagName?e.tagName.toLowerCase():''})()";}
static void PH26CaptureSelector(id m,WKWebView*w,NSInteger attempts){if(!m||!w||attempts<=0)return;[w evaluateJavaScript:PH26SelectorFromSelectedElementJS() completionHandler:^(id result,NSError*error){dispatch_async(dispatch_get_main_queue(),^{NSString*s=(!error&&[result isKindOfClass:NSString.class])?result:@"";if(s.length){PH26SetSelectedSelector(m,s);return;}dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(.12*NSEC_PER_SEC)),dispatch_get_main_queue(),^{PH26CaptureSelector(m,w,attempts-1);});});}];}
static void PH26Highlight(id m,SEL cmd,WKWebView*w,CGFloat x,CGFloat y){if(PH26OriginalHighlight)((void(*)(id,SEL,WKWebView*,CGFloat,CGFloat))PH26OriginalHighlight)(m,cmd,w,x,y);PH26SetSelectedSelector(m,@"");PH26CaptureSelector(m,w,5);}
static void PH26SetJSONText(id self,NSString*s){NSString*j=PH26FilterJSON(s?:@"");objc_setAssociatedObject(self,PH26JSONTextKey,j,OBJC_ASSOCIATION_COPY_NONATOMIC);@try{[self setValue:j forKey:@"currentDetails"];[self setValue:@"Filtro JSON" forKey:@"currentSubtitle"];}@catch(__unused NSException*e){}}
static void PH26RenderJSON(id self){PH26SetWantsJSON(self,YES);PH26SetJSONScreen(self,YES);((void(*)(id,SEL,BOOL))objc_msgSend)(self,@selector(render:),YES);}
static void PH26JSONTapped(id self,SEL cmd){PHOverlayManager*m=[PHOverlayManager sharedManager];WKWebView*w=nil;@try{w=[m valueForKey:@"highlightedWebView"];}@catch(__unused NSException*e){}NSString*c=PH26SelectedSelector(m);if(c.length){PH26SetJSONText(self,c);PH26RenderJSON(self);return;}if(![w isKindOfClass:WKWebView.class]){PH26SetJSONText(self,@"");PH26RenderJSON(self);return;}[w evaluateJavaScript:PH26SelectorFromSelectedElementJS() completionHandler:^(id result,NSError*error){dispatch_async(dispatch_get_main_queue(),^{NSString*s=(!error&&[result isKindOfClass:NSString.class])?result:@"";if(s.length)PH26SetSelectedSelector(m,s);PH26SetJSONText(self,s);PH26RenderJSON(self);});}];}
static UIButton*PH26Button(id self,SEL cmd,NSString*title,SEL action){if(action==@selector(backTapped)&&PH26WantsJSON(self)&&!PH26JSONScreen(self)){title=@"JSON";action=@selector(ph_jsonTapped26);}else if(action==@selector(backTapped)&&PH26JSONScreen(self)){title=@"Voltar";action=@selector(backTapped);}if(PH26OriginalButton)return((UIButton*(*)(id,SEL,NSString*,SEL))PH26OriginalButton)(self,cmd,title,action);return nil;}
static void PH26Hierarchy(id self,SEL cmd){PH26SetJSONScreen(self,NO);PH26SetWantsJSON(self,YES);if(PH26OriginalHierarchy)((void(*)(id,SEL))PH26OriginalHierarchy)(self,cmd);}
static void PH26Back(id self,SEL cmd){PH26SetJSONScreen(self,NO);PH26SetWantsJSON(self,NO);if(PH26OriginalBack)((void(*)(id,SEL))PH26OriginalBack)(self,cmd);}
static void PH26Details(id self,SEL cmd,NSString*d,NSString*s){PH26SetJSONScreen(self,NO);PH26SetWantsJSON(self,NO);if(PH26OriginalDetails)((void(*)(id,SEL,NSString*,NSString*))PH26OriginalDetails)(self,cmd,d,s);}
@interface PHV26JSONFlowFinal:NSObject@end
@implementation PHV26JSONFlowFinal
+ (void)load{Class target=NSClassFromString(@"PHInspectorViewController"),manager=NSClassFromString(@"PHOverlayManager");if(!target)return;class_addMethod(target,@selector(ph_jsonTapped26),(IMP)PH26JSONTapped,"v@:");Method button=class_getInstanceMethod(target,@selector(button:action:));if(button){PH26OriginalButton=method_getImplementation(button);method_setImplementation(button,(IMP)PH26Button);}Method hierarchy=class_getInstanceMethod(target,@selector(hierarchyTapped));if(hierarchy){PH26OriginalHierarchy=method_getImplementation(hierarchy);method_setImplementation(hierarchy,(IMP)PH26Hierarchy);}Method back=class_getInstanceMethod(target,@selector(backTapped));if(back){PH26OriginalBack=method_getImplementation(back);method_setImplementation(back,(IMP)PH26Back);}Method details=class_getInstanceMethod(target,@selector(showInspectorDetails:subtitle:));if(details){PH26OriginalDetails=method_getImplementation(details);method_setImplementation(details,(IMP)PH26Details);}if(manager){Method highlight=class_getInstanceMethod(manager,@selector(highlightWebElementInWebView:x:y:));if(highlight){PH26OriginalHighlight=method_getImplementation(highlight);method_setImplementation(highlight,(IMP)PH26Highlight);}}}
@end
