#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>
#import <objc/runtime.h>

static NSString *PHV21FilterPath(void){static NSString*path;static dispatch_once_t once;dispatch_once(&once,^{NSString*home=NSHomeDirectory();NSDirectoryEnumerator*e=[NSFileManager.defaultManager enumeratorAtPath:home];NSString*r=nil;while((r=[e nextObject]))if([r.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"]){path=[home stringByAppendingPathComponent:r];break;}if(!path.length)path=[home stringByAppendingPathComponent:@"Documents/custom-filters.json"];});return path;}
static NSDictionary *PHV21NativeFilter(NSDictionary*f,NSString*override){if(![f isKindOfClass:NSDictionary.class])return nil;NSDictionary*a=[f[@"action"] isKindOfClass:NSDictionary.class]?f[@"action"]:nil;NSDictionary*t=[f[@"trigger"] isKindOfClass:NSDictionary.class]?f[@"trigger"]:nil;NSString*s=override.length?override:nil;if(!s.length)s=[a[@"selector"] isKindOfClass:NSString.class]?a[@"selector"]:nil;if(!s.length)s=[f[@"selector"] isKindOfClass:NSString.class]?f[@"selector"]:nil;if(!s.length)return nil;return @{@"action":@{@"type":[a[@"type"] isKindOfClass:NSString.class]?a[@"type"]:@"css-display-none",@"selector":s},@"trigger":@{@"url-filter":[t[@"url-filter"] isKindOfClass:NSString.class]?t[@"url-filter"]:@".*"}};}
static void PHV21NormalizeSavedFilters(NSString*stable){NSString*path=PHV21FilterPath();NSData*data=[NSData dataWithContentsOfFile:path];if(!data)return;id root=[NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:nil];NSArray*filters=nil;if([root isKindOfClass:NSDictionary.class])filters=[root[@"filters"] isKindOfClass:NSArray.class]?root[@"filters"]:nil;else if([root isKindOfClass:NSArray.class])filters=root;if(!filters)return;NSMutableArray*native=[NSMutableArray arrayWithCapacity:filters.count];for(NSUInteger i=0;i<filters.count;i++){NSDictionary*c=PHV21NativeFilter(filters[i],i==filters.count-1?stable:nil);if(c)[native addObject:c];}NSData*out=[NSJSONSerialization dataWithJSONObject:native options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];if(out)[out writeToFile:path atomically:YES];}
static NSString*PHV21StableSelectorScript(void){return @"(function(){var e=document.querySelector('[data-projetoh-selected=\\\"1\\\"]');if(!e)return '';function esc(s){try{return CSS.escape(s)}catch(_){return s.replace(/[^a-zA-Z0-9_-]/g,'\\\\$&')}}function unique(sel){try{return document.querySelectorAll(sel).length===1}catch(_){return false}}function classCandidates(n){if(!n||typeof n.className!=='string')return [];var a=n.className.trim().split(/\\s+/).filter(Boolean);var preferred=a.filter(function(c){return c==='q-page-sticky'||c.indexOf('page-sticky')>=0||c.indexOf('floating')>=0||c.indexOf('component')>=0||c.indexOf('overlay')>=0||c.indexOf('panel')>=0;});var normal=a.filter(function(c){return ['row','col','flex','flex-center','justify-center','items-center','no-wrap','q-focus-helper','q-icon','q-btn','q-btn__content','q-btn-item','non-selectable','notranslate','material-icons','mobile','platform-ios','touch'].indexOf(c)<0;});return preferred.concat(normal.filter(function(c){return preferred.indexOf(c)<0;}));}function findStable(start){var n=start;while(n&&n.nodeType===1&&n!==document.body){if(n!==start&&n.id){var id='[id=\\\"'+esc(n.id)+'\\\"]';if(unique(id))return id;}var cs=classCandidates(n);for(var i=0;i<cs.length;i++){var s='.'+esc(cs[i]);if(unique(s))return s;}n=n.parentElement;}if(start.id){var sid='[id=\\\"'+esc(start.id)+'\\\"]';if(unique(sid))return sid;}var own=classCandidates(start);for(var j=0;j<own.length;j++){var os='.'+esc(own[j]);if(unique(os))return os;}return '';}return findStable(e);})()";}
static IMP PHV21OriginalSave=NULL;
static void PHV21SavePendingFilters(id self,SEL _cmd){if(PHV21OriginalSave)((void(*)(id,SEL))PHV21OriginalSave)(self,_cmd);WKWebView*webView=nil;@try{webView=[self valueForKey:@"highlightedWebView"];}@catch(__unused NSException*e){}if(![webView isKindOfClass:WKWebView.class]){PHV21NormalizeSavedFilters(nil);return;}[webView evaluateJavaScript:PHV21StableSelectorScript() completionHandler:^(id result,NSError*error){NSString*stable=(!error&&[result isKindOfClass:NSString.class]&&[(NSString*)result length])?result:nil;PHV21NormalizeSavedFilters(stable);}];}
__attribute__((constructor))static void PHV21Install(void){dispatch_async(dispatch_get_main_queue(),^{Class cls=NSClassFromString(@"PHOverlayManager");if(!cls)return;Method method=class_getInstanceMethod(cls,@selector(savePendingFilters));if(!method)return;IMP current=method_getImplementation(method);if(current==(IMP)PHV21SavePendingFilters)return;PHV21OriginalSave=current;method_setImplementation(method,(IMP)PHV21SavePendingFilters);});}
